language: csharp
solution: TracingSOE.sln
install:
  - nuget restore TracingSOE.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TracingSOE.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TestTraceSOE/bin/Release/TestTraceSOE.dll